# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160412_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=datetime.datetime(2016, 6, 22, 16, 35, 38, 925452, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
