# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160623_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('SNT Council', 'SNT Council'), ('Games and Sports', 'Games and Sports'), ('Cultutal Council', 'Cultutal Council'), ('FMC', 'FMC'), ('Vox Populi', 'Vox Populi'), ('Senate', 'Senate')], max_length=120, null=True),
        ),
    ]
