# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160625_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default=datetime.datetime(2016, 7, 28, 19, 24, 0, 330257, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
